sudo: false

language: php

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_TRAVISCI=phpcs

before_script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs
    fi
  - if find . -name "*.php" ! -path "./vendor/*" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi
